### PR TITLE
Improve DevContainer

### PR DESCRIPTION
**Pull request by vvmruder**
add zsh as in container standard shell

### CODE REVIEW

**Review by marionb — APPROVED** [review]
It works. The auto completion is working well on the first word of the command but id there is a second part it is a bit odd (like `make` is recognized but then it stops). It is still an improvement :-D

**Comment by kdeininger** [comment]
Maybe the zsh-completions need to be installed:
https://github.com/zsh-users/zsh-completions

Alternatively, we could use bash.

**Comment by vvmruder** [comment]
If I use `make c` and then press tab I get `clean` and `clean-all` as candidates. What would you suggest would be the right behavior?

**Comment by marionb** [comment]
> If I use make c and then press tab I get clean and clean-all as candidates. What would you suggest would be the right behaviour?

that would be the behaviour I'd expect after a restart of my pc that seems to also be working now :+1: (was not expecting to have to restart).

**Comment by vvmruder** [comment]
@kdeininger I thought zsh would be nice because it is more integrated with git for instance and also offers many plugins for a feature rich behavior

**Pull request merged**
