### PR TITLE
Attribute office_at_web becomes a multilingual dictionary

### PR DESCRIPTION
**Pull request by vuilleumierc**
Issue #1172

### CODE REVIEW

**Comment by vvmruder** [comment]
Bildschirmfoto 2021-06-29 um 15 41 02

Proof of working code for a XML extract (JSON is missing for now). I used the following link:
http://localhost:6543/oereb/extract/reduced/xml/CH113928077734

Maybe you need to start with `make clean serve-dev` to newly import updated test dev data on server startup?

**Comment by vuilleumierc** [comment]
Thanks for checking. The XML works for me too, but the structure does not seem to be correct in the JSON extract
image

**Comment by vvmruder** [comment]
Ok. Will do further checks

**Comment by voisardf** [comment]
I'm not sure, but isn't the flattening for the JSON done in the contrib print_proxy? If so, there might be an adaption missing for this attribute?

**Comment by vuilleumierc** [comment]
I found the problem (see commit 476ace9) but I will check also with mapfish_print

**Comment by vvmruder** [comment]
Problem is probably somewhere here: https://github.com/openoereb/pyramid_oereb/blob/b20ebb5ab36b3aa888fbad083e6bc18fb1d04c36/pyramid_oereb/lib/renderer/extract/json_.py#L454-L455

**Comment by vvmruder** [comment]
> I found the problem (see commit [476ace9](https://github.com/openoereb/pyramid_oereb/commit/476ace9a2e96745845de0b53e0fe9341c6acb54f)) but I will check also with mapfish_print

Exactly :D

Good catch

**Comment by voisardf** [comment]
👍

**Review by voisardf — APPROVED** [review]
Looks good to me, thanks

**Comment by vvmruder** [comment]
Did you tried `make test`?

**Comment by vuilleumierc** [comment]
Good point, I hadn't done it since my last commits :) it is fixed

**Comment by vvmruder** [comment]
@vuilleumierc I added the multilingual attribute also in some places for the test data. It came to my curiosity why checks are still ok. Especially the checks against the xml schema. After changing to multilingual they should fail. So I updated the used test data as well to cover also this case now.

**Review by vvmruder — APPROVED** [review]
I think now its pretty complete. Congrats for this fast and nice work.

**Pull request merged**
