### PR TITLE
Fix test core/sources

### PR DESCRIPTION
**Pull request by vuilleumierc**

### CODE REVIEW

**Comment by vvmruder** [comment]
@vuilleumierc I tried to check your branch. It but checked out freshly and doing a `make build` gives me suddenly an error:

```
.venv/bin/python dev/database/load_sample_data.py --configuration pyramid_oereb.yml --sql-file dev/database/structure/03_fill_dev_tables.sql --dir dev/sample_data
Traceback (most recent call last):
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 228, in <module>
    _run()
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 218, in _run
    SampleData(
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 131, in load
    self._load_sample(class_, file_name)
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 90, in _load_sample
    self._do_sql_insert(sql, r)
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 68, in _do_sql_insert
    sql = re.sub(r":{}\b".format(re.escape(k)), self._format_value(v), sql)
  File "/home/kalle/projects/openoereb/pyramid_oereb/dev/database/load_sample_data.py", line 57, in _format_value
    raise LookupError("Unsupported type {}".format(type(value)))
LookupError: Unsupported type <class 'list'>
make: *** [Makefile:223: dev/database/structure/03_fill_dev_tables.sql] Error 1

```

**Comment by vvmruder** [comment]
Ok. But why was this not a problem on master until now?

**Comment by vvmruder** [comment]
Another question is: Is this ready for review? I get the idea this is a draft still. Right?

**Review by mki-c2c — APPROVED** [review]
It's a good idea to separate the test data from dev data.
We can discuss about changing all test data to python instead of json, since there is no need to exchange / share this data, it will be exclusive to the tests.

**Comment by vvmruder** [comment]
@mki-c2c I agree to the separation. And from my point of view it can stay as JSON where necessary. I was just curious why it came to the decision. Nevermind

**Comment by mki-c2c** [comment]
> @mki-c2c why it came to the decision.

You mean the decision to separate the data ? It's just going the path of least resistance to get the CI working. And it required some modification to dev data breaking the build. So we separated the data. Once the CI is working, we can improve the tests.

**Comment by vuilleumierc** [comment]
> which fails on 29 Tests because of missing config object and Database. I think calling the tests like this is not working. Right? How do you run them?

You probably have a DB port mismatch because it had been changed in another PR on the base branch. If you try on our main branch `1421-fix-fixtures` it should work now

**Comment by mki-c2c** [comment]
@vvmruder 
actually we called directly the pytest command or updated the command in the makefile to select test files and folders instead of using an ENVVAR.

However, CI and tests are now fixed (some tests missing in the core root dir) https://github.com/openoereb/pyramid_oereb/pull/1427/commits/409340ee21ff9137e3a34109d0624dfed52a5e53

so now you can run `make test-core` (as in the CI)

**Comment by vvmruder** [comment]
@mki-c2c Thank you for reply and good to see that CI is running again. I will leave it for now. I get errors locally when running the make command outside docker because of numpy build.
```
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```

**Comment by mki-c2c** [comment]
yes, it will be important to have a reliable local test environment as well. We can look into this later. Trying to finish the core tests in CI, then we can have a look at open issues tomorrow.
(and good luck for your numpy...)

**Pull request merged**
