### PR TITLE
Remove transparency from logos

### PR DESCRIPTION
**Pull request by vuilleumierc**
After careful inspection it appeared that there was an alpha channel in all Confederation logos (ch and ch.plr) and in our sample canton logo. This was the problem blocking the PDFA-1 compliance. 
Here are the images without transparency:
[logos-no-alpha.zip](https://github.com/openoereb/pyramid_oereb/files/7168319/logos-no-alpha.zip)
 ~~This PR adds them in our sample data but they should still be updated on the Confederation's side (OeREBKRM_V2_0_Logos_XXXXXXXX.xml)~~

Edit: @voisardf I replaced the ch and ch.plr logos with the images from OeREBKRM_V2_0_Logos_20210915.xml 
Here it works fine for de, fr, and it but not rm. The image ch.plr.rm does not seem to be valid (I cannot decode it)

Closes https://github.com/openoereb/pyramid_oereb/issues/1311
Closes https://github.com/openoereb/pyramid_oereb/issues/1299
Closes https://github.com/openoereb/pyramid_oereb/issues/1296

### CODE REVIEW

**Comment by voisardf** [comment]
@vuilleumierc : ping me once the new logo file is integrated and I'll check

**Comment by voisardf** [comment]
there you go 😉 @vuilleumierc

**Comment by vuilleumierc** [comment]
@voisardf Works now in rm, thanks a lot! For en I get 400 bad request but this has nothing to do with the logos https://github.com/openoereb/pyramid_oereb/blob/93c3ccc03f9af8e9e6a5f9f6767977982e4bbc16/pyramid_oereb/standard/pyramid_oereb.yml.mako#L14-L21
Should we merge this?

**Comment by voisardf** [comment]
@vuilleumierc: Good to go for me

**Pull request merged**
