### PR TITLE
Improving GetEGRID performance

### PR DESCRIPTION
**Pull request by peterschaer**
With this change the request time goes down to 200ms on my development environment. On production it may even be quicker. Maybe someone has a more elegant solution.

### CODE REVIEW

**Comment by peterschaer** [comment]
This PR tries to fix #1679

**Review by michmuel — APPROVED** [review]
Looks good and works in our environment. I did not test the improvement in performance.

**Review by vvmruder — APPROVED** [review]
This is a good catch. It goes in the right direction-since we load config on server boot, the next improvement can be based on that. THX @peterschaer

**Comment by jwkaltz** [comment]
Hi @peterschaer , please feel free to merge your request.

**Pull request merged**
