### PR TITLE
Fix JSON response of GetEgrid

### LINKED ISSUE #1530: JSON response of GetEgrid is invalid
The attribute `type` needs to be encoded as `RealEstateType` containing a valid `Code` and a `MultilingualText`.

```json
...
"type": {
  "Code": "RealEstate",
  "Text": [
    {
      "Language": "de",
      "Text": "Liegenschaft"
    }
  ]
}
...
```

### PR DESCRIPTION
**Pull request by kdeininger**
Closes #1530

### CODE REVIEW

**Comment by kdeininger** [comment]
As the service provides no parameter to specify the language, the real estate type is returned containing all available and configured languages (similar to capabilities).

**Comment by vvmruder** [comment]
Did you checked this also for the XML?

**Comment by jwkaltz** [comment]
@vvmruder @kdeininger what was the conclusion regarding the question about whether a fix is also needed for the XML?
Jura is reporting that the getegrid/xml is not working (but the getegrid/json is working)

**Comment by kdeininger** [comment]
The getegrid/xml was working and valid before. I think the following line

https://github.com/openoereb/pyramid_oereb/blob/e72a9e96b8516166fe463e054937b726f1e314a1/pyramid_oereb/core/renderer/getegrid/templates/xml/getegrid.xml#L19

needs to be changed as `Config.get_real_estate_type_by_data_code()` has already been called here:

https://github.com/openoereb/pyramid_oereb/blob/e72a9e96b8516166fe463e054937b726f1e314a1/pyramid_oereb/core/views/webservice.py#L473

**Comment by kdeininger** [comment]
@jwkaltz XML should be fixed with https://github.com/openoereb/pyramid_oereb/pull/1545.

**Pull request merged**
