### PR TITLE
Improve test coverage for Interlis 2.3 data sources

### PR DESCRIPTION
**Pull request by voisardf**
improving test coverage for hook_methods in the interlis 2.3 sources

### CODE REVIEW

**Comment by voisardf** [comment]
@vvmruder @michmuel @svamaa I recycled the fixtures from the standard/conftest.py - so there are more definitions already in there then I use for the hook_methods.
What do you prefer: Should I remove the elements we do not need (yet), adding them again as we add test cases, or should we do a check and remove what is potentially not needed once we finished with adding tests?

**Comment by svamaa** [comment]
> ve what is potentially not needed once we finished with adding t

I'd delete all that's not needed now. We still have all the fixtures in the code history if needed. I think this way it's easier to avoid unneeded code and keep the overview on the needed fixtures.

**Comment by voisardf** [comment]
cleaned up and ready for review

**Review by michmuel — APPROVED** [review]
Lokks good to me.

**Review by vvmruder — APPROVED** [review]
Here and there it could be improved. But it is a good start. :+1:

**Review by svamaa — APPROVED** [review]

**Comment by voisardf** [comment]
@vvmruder I'll wait for your review before I merge

**Pull request merged**
