### PR TITLE
add optional tolerance on geometric operations

### PR DESCRIPTION
**Pull request by mki-c2c**
tolerance can be configured on plr base in yaml file as shown below:

if there is a tolerance, geometries are compared with buffer / distance
if there is no defined tolerance, the simple operations are used (Intersects / Intersection)
```
pyramid_oereb:
  plrs:
    - code: ch.Nutzungsplanung
      geometry_type: GEOMETRYCOLLECTION
      thresholds:
        length:
          limit: 1.0
          unit: 'm'
          precision: 2
        area:
          limit: 1.0
          unit: 'm²'
          precision: 2
        percentage:
          precision: 1
      tolerance: 0.00001
```

### CODE REVIEW

**Comment by vvmruder** [comment]
@mki-c2c 
Would it make sense to offer this not only for the standard source but also for the rest? Like Interlis? Maybe it is not relevant because it is solved through inheritance already: https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/data_sources/interlis_2_3/sources/plr.py

But maybe you could have a look.

**Comment by mki-c2c** [comment]
yes I'll have a look at the tolerances in Interlis.
Thanks for the hint

**Comment by voisardf** [comment]
@mki-c2c @jwkaltz Could you tell me who (which canton) asked for this enhancement?

**Comment by jwkaltz** [comment]
> @mki-c2c @jwkaltz Could you tell me who (which canton) asked for this enhancement?

It comes from Geoinfo (I don't remember if it was Appenzell or St.Gallen). So far they have implemented successfully the solution that @svareg proposed, which needs a database adaptation, but Geoinfo would like to obtain the same effect without needing database changes.
So in the end, this might also be interesting for Basel-Stadt.

**Comment by mki-c2c** [comment]
@vvmruder 
I have added the tolerance also for Interlis mode. Thanks for the suggestion.

**Review by vvmruder — APPROVED** [review]
for me this looks good now.

**Pull request merged**
