### PR TITLE
create test fixture with Config patch and fix records tests

### PR DESCRIPTION
**Pull request by mki-c2c**
fix of one series of tests

### CODE REVIEW

**Comment by mki-c2c** [comment]
the tests in core/records and core/renderer have been technically fixed.
The correctness of the contents has to be checked, expecially the following test cases:

- [ ] law_status document_type has changed from str to DocumentTypeRecord [here](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/records/test_document.py#L81)
- [ ] date changed from UpdateDateOS to UpdateDateCS [here](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/renderer/test_json.py#L126)
- [ ] postal code changed from int to str [here](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/renderer/test_json.py#L178)
- [ ] code chenged from Liegenschaft to RealEstate, MunicipalityCode instead of FosNr, MunicipalityName instead of Municipality [here](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/renderer/test_json.py#L212-L217)
- [ ] DocumentType becomes Type in [test_json](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/renderer/test_json.py#L392)
- [ ] geometry type added  in [json geometry export](https://github.com/openoereb/pyramid_oereb/blob/1421-fix-records/tests/core/renderer/test_json.py#L461)

**Comment by vvmruder** [comment]
Hi @mki-c2c . Do you have time for a meeting on this PR? Just to coordinate things.

**Review by vvmruder — CHANGES_REQUESTED** [review]
Maybe remove XML/JSON validation at all. I added an Issue to solve this with E2E tests. #1436

**Review by vuilleumierc — APPROVED** [review]
LGTM thanks a lot. I would just add the dependency to `pyramid_oereb_test_config` for the tests that need it and I have one more comment about the geometry tests (see below)

**Pull request merged**
