### PR TITLE
Fix creation of standart tables

### PR DESCRIPTION
**Pull request by marionb**
TODO:

- [x] Take apart table creation for OEREBlex and standard tables
- [x] Create the Main schema separateness from the theme tables

Currently I have noticed the following issues (might not be cause by the changes from this PR):

- When building the image new and removing all the containers there is an issue that the test db is not there. The PostgreSQL container continuously logs: `` The issue disappear after having run the tests once. (the application seems to be running)
- Running the tests twice:
    1. Run: the test pass
    2. Run: there is an issue because the containers have been stopped and can no longer be accessed by the tests
- Multiple `oereb/main_container` exist simultaneously

### CODE REVIEW

**Review by vvmruder — APPROVED** [review]
great :+1:

**Review by vvmruder — APPROVED** [review]

**Comment by marionb** [comment]
@vvmruder thanks for the review. I'll merge the PR in to yours is that OK?

**Comment by marionb** [comment]
@vvmruder Thanks for the review.
I'll mere this in to your branch then you can merge in to maser once your branch is done?
I am not sure why but somehow the base branch has now changed to master.

**Comment by vvmruder** [comment]
@marionb I already merged the branch you are based on. **So you have to merge into master.** But you need to rebase probably locally on origin/master. If you need help let me know.

**Comment by vvmruder** [comment]
@marionb I think this can be closed in the favor of #1547 ?

**Pull request closed without merging**
