### PR TITLE
use unique entry point for all tests both in CI and daily checks

### PR DESCRIPTION
**Pull request by mki-c2c**
daily checks broke because contrib tests were renamed

### CODE REVIEW

**Review by vvmruder — APPROVED** [review]

**Comment by vvmruder** [comment]
In this context it might be useful to also separate tests of contrib stats (https://github.com/openoereb/pyramid_oereb/tree/master/pyramid_oereb/contrib/stats) into a separate part to support the new project/test structure?

**Comment by mki-c2c** [comment]
> In this context it might be useful to also separate tests of contrib stats (https://github.com/openoereb/pyramid_oereb/tree/master/pyramid_oereb/contrib/stats) into a separate part to support the new project/test structure?

Currently the stats / logging tests are done in core: https://github.com/openoereb/pyramid_oereb/blob/fix_daily_check/tests/core/test_logger.py.  Should they be part of contrib ?

**Comment by vvmruder** [comment]
I think we should provide it like we provide teh tests for other contrib stuff like here: https://github.com/openoereb/pyramid_oereb/blob/fix_daily_check/Makefile#L293-L294

In for the stats this would mean to have a target like: `test-contrib-stats` and the test files situated in the the already prepared folder: https://github.com/openoereb/pyramid_oereb/tree/fix_daily_check/tests/contrib.stats

**Comment by vvmruder** [comment]
but we can solve this in an additional PR

**Review by vvmruder — APPROVED** [review]
:star_struck: I like it-now it really gets shape Thank you!!!

**Pull request merged**
