### PR TITLE
Conditionally add SLD_VERSION for legend_at_web

### LINKED ISSUE #1022: Add SLD_VERSION in URL for legend_at_web
The import script for the federal topic data uses the URL from `reference_wms` if no value for `legend_at_web` is specified. The parameters are adjusted according to the `GetLegendGraphic` request.

Using WMS version 1.3.0, an additional parameter needs to be added to the request: `SLD_VERSION=1.1.0`.

This can be applied on parsing the view service:

https://github.com/openoereb/pyramid_oereb/blob/07e91104f0b8d40b99fddbaf6634f114c6515d30/pyramid_oereb/standard/xtf_import/view_service.py#L54-L57

### PR DESCRIPTION
**Pull request by kdeininger**
Add `SLD_VERSION` parameter at `GetLegendGraphic` request for WMS version 1.3.0.

Closes #1022

### CODE REVIEW

**Comment by pfirpfel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyramid_oereb/standard/xtf_import/view_service.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/pyramid_oereb/pyramid_oereb/pullRequest?prid=5278067&bid=17283104)

**Comment by pfirpfel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyramid_oereb/standard/xtf_import/view_service.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/pyramid_oereb/pyramid_oereb/pullRequest?prid=5278067&bid=17283104)

**Comment by pfirpfel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyramid_oereb/standard/xtf_import/view_service.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/pyramid_oereb/pyramid_oereb/pullRequest?prid=5278067&bid=17283104)

**Comment by kdeininger** [comment]
@vvmdipie made some tests on our dev instance by changing the WMS version in the view service data. He noticed the missing SLD_VERSION in `legend_at_web`. After adding this parameter, everything worked as expected using WMS version 1.3.0.

**Pull request merged**
