### PR TITLE
Real Estate Type adjustments

### PR DESCRIPTION
**Pull request by svamaa**

### CODE REVIEW

**Comment by vvmruder** [comment]
The tests need to be updated and fixed indeed. And you should solve the conflicts with the master branch.

**Review by vvmruder — CHANGES_REQUESTED** [review]
The following tests should be fixed:

- `FAILED tests/renderer/test_json.py::test_format_real_estate - AssertionError: assert {'Canton': 'BL',\n 'EGRID': 'CH77597921171...`
- `FAILED tests/test_config.py::test_parse_configuration - pyramid.exceptions.ConfigurationError: Missing configuration for themes`

Otherwise I'am ok with this PR.

**Review by voisardf — APPROVED** [review]
Thanks a lot! Just a naming suggestion (I also plan to change my DocumentTypeText classes name) and a few minor comments.
Looks good to me otherwise. I have not tested it locally, I trust @vvmruder did it.

**Review by vvmruder — APPROVED** [review]
Now I'am happy :)

Thanks a lot for this.

**Pull request merged**
