### PR TITLE
Fix layers when merging themes

### LINKED ISSUE #1702: Missing layers in base layers when grouping PLRs
When PLRs are grouped because they have the same theme, only the first Reference WMS is respected for the generation ob the `baseLayers` attribute. The expected behavior would be that all the layers and base URLS add used also in the print sec.
For example:

This json
```
https://oereb.zg.ch/oereb/extract/json?EGRID=CH407765770667
RestrictionOnLandownership: [
	{
	Theme: {
		Code: "ch.ZG.Nutzungsplanung",
		Text: ...
		}
	...
	Map: {
		ReferenceWMS: [
			{
				Language	"de",
				Text	"https://services.geo.zg.ch/ows-oereb/Nutzungsplanung?...&LAYERS=ch.zg.nutzungsplanung.grundnutzung"
			}],
		...
	},{
	Theme: {
		Code: "ch.ZG.Nutzungsplanung",
		Text: ...
		}
	...
	Map: {
		ReferenceWMS: [
			{
				Language	"de",
				Text	""https://services.geo.zg.ch/ows-oereb/Nutzungsplanung?...&LAYERS=ch.zg.nutzungsplanung.ueberlagernde_zonen""
			}],
		...
	}]
```
turns in to this print spec:
```
https://oereb.zg.ch/oereb/extract/pdf?EGRID=CH407765770667&getspec=true
"baseLayers": {
    "layers": [
        {
            "baseURL": "https://services.geo.zg.ch/ows-oereb/Nutzungsplanung",
            "customParams": {
                "TRANSPARENT": "true"
            },
            "imageFormat": "image/png",
            "layers": [
                "ch.zg.nutzungsplanung.grundnutzung"
            ],
            ...
        }, ...
```

Note only the first layer is added in specs for MFP

### PR DESCRIPTION
**Pull request by marionb**
Fixes #1702

### CODE REVIEW

**Review by jwkaltz — APPROVED** [review]
LGTM

**Comment by michmuel** [comment]
@marionb, @jwkaltz The tests were not successful. Is maybe a rebase required?

**Comment by marionb** [comment]
@michmuel I re-ran all the jobs now they seem to pass. I don't see that there are conflicts with the master branch (concerning re-base but thanks for the hint :-) ).

**Comment by marionb** [comment]
@michmuel

**Review by michmuel — APPROVED** [review]
Looks good to me.

However, one question: When PLRs of a specific theme relate to more than one layer of a view service (PLR1->layer1, PLR2->layer2) and the draw order of the layers is important (layer2 on top of layer1). How do you ensure that?

**Comment by marionb** [comment]
hmm that is a good question I don't think we ensure that. Do we have an indexing system that we should considering? Where would the order be defined?
Currently it just adds the first layer at the top.
Fact is I am not sure that we are ensuring this at the moment so I think this is another issue to be solved probably separately. Or did I miss understand this?

**Comment by michmuel** [comment]
In the "Rahmenmodel", a parameter "LayerIndex" is part of the data extract (https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/publication/instruction.download/cadastre-internet/de/documents/oereb-weisungen/Rahmenmodell-de.pdf, page 48). However, it is not part of the transfer structure.

If using the standard or the oereblex models, the layer index of the view service should be usable and should be exported to the extracts (not used or tested by us).
See here:
https://github.com/openoereb/pyramid_oereb/blob/6af0e5cfadf52bf3740dd9b7e4ac086c99bb86f9/pyramid_oereb/contrib/data_sources/standard/models/__init__.py#L173

**Comment by michmuel** [comment]
I would check if sorting matters for the cantons using several view services for a theme before investing much time on it. Merging this PR and solving the sorting issue later seems reasonable.

**Comment by marionb** [comment]
@michmuel Thanks

**Pull request merged**
