### PR TITLE
[WIP] Fix polygon GML rendering

### PR DESCRIPTION
**Pull request by kdeininger**
Exterior ring has been rendered also as interior ring.

### CODE REVIEW

**Comment by jwkaltz** [comment]
@kdeininger is this related to #742? (from the description, it does not seem to be exactly related, but I am not sure)

**Comment by vvmruder** [comment]
indeed, this need further discussion

**Comment by jwkaltz** [comment]
@kdeininger @vvmruder we must release 1.5.0 today, is this ready to merge from your point of view, or shall we put it in a later version?

**Comment by vvmruder** [comment]
> @kdeininger is this related to #742? (from the description, it does not seem to be exactly related, but I am not sure)

We should solve poslist in another PR. This one can be merged since it solves a really existing bug. The issue you mentioned was more about reducing XML data overhead

**Pull request merged**
