### PR TITLE
Adapt Topic Page

### LINKED ISSUE #1215: PDF: Topic Page
Given the introduction of a third legal status, the topic page comes now in different 'flavours' depending on the status.
For each topic, subtopic and status providing results for this real estate a separate page has to be added in a predefined order.

?? Question to clarify with confederation: If a real estate is not touched by one ore two of the three legal status, but there are results contained in the bounding box (e.g. adjacent real estate is concerned) should the page be created anyway? 

Details on pages 15 ff and 24 of the specification: https://github.com/openoereb/pyramid_oereb/files/6442522/Weisung-statischer-Auszug-de.pdf

### What needs to be done:
- [x] Rearrange page title adding subtopic (if existing) and the legal state as subtitle -> PR #1306
- [x] Make sure the predefined titles from http://models.geo.admin.ch/V_D/OeREB/ > OeREBKRM_V2_0_Themen_[update_date].xml are used for the mandatory topics -> #1317
- [x] Remove complete legend element - remove `CompleteLegendLabel` and `legend`
- [x] Adapt legal document sorting to the new indexing system
- [x] Check that only the attribute title for legal documents is uses; official_title has been removed
- [x] Check that the official number is displayed as requested by the specifications -> this is given as a `MultilingualText`: it is what we currently have.
- [x] Verify layout conformance (spacing, padding, dimensions, font sizes)
- [x] Check for renamed attributes

### PR DESCRIPTION
**Pull request by marionb**
closes #1215
TOTEST:
- use the mfp pr https://github.com/openoereb/pyramid_oereb_mfp/pull/80
- turn off pdfA. For instructions on this see https://github.com/openoereb/pyramid_oereb_mfp/pull/77

TODO:
- [x] fix test_get_sorted_hints
- [x] fix test_get_sorted_law 
- [x] fix mfp extract test

### CODE REVIEW

**Comment by marionb** [comment]
I need to still fix two tests for this, the rest is ready for a review if any one wants to already take a look.

**Comment by vuilleumierc** [comment]
The extracts (JSON, XML, PDF) work fine here :+1:

**Comment by voisardf** [comment]
I confirm that 👍 🙂

**Review by voisardf — COMMENTED** [review]
Code looks good, local instance gets me working XML/JSON and PDF extracts.
I still have the two additional tests failing as you said. Once they are solved PR is ok for me 🙂

**Comment by voisardf** [comment]
let me try it locally once. should not take more than half an hour

**Comment by voisardf** [comment]
All good. Feel free to merge. I got XML/JSON and PDF extracts in de,fr,it,rm 😃
[20210916125308_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/7177853/20210916125308_extract.pdf)

Some translations things to verify for our final release as there were some "de" elements in the data-extract while asking for another language. I guess it's working fallback policy. I make a note, no need to investigate for now.

**Comment by voisardf** [comment]
ah not to forget, I got the rm PDF because I locally pulled the master into PR https://github.com/openoereb/pyramid_oereb_mfp/pull/80
and I think we may discard https://github.com/openoereb/pyramid_oereb_mfp/pull/77 now as we have a working pdf-a?

**Pull request merged**
